"""
services/exterior_design_service.py
------------------------------------
Generates a 3D architectural exterior design visualization using the
Google GenAI API (Gemini 3.1 Flash Image by default).

Takes both the architectural report text (from main agent) and the generated
2D floor plan image bytes (from floor_plan_service) as multimodal input.

Public API
----------
generate_exterior_design(
    report_text        : str,
    floor_plan_bytes   : bytes | None = None,
    style              : str | None   = None,
    api_key            : str | None   = None, # falls back to GEMINI_API_KEY in .env
    model              : str | None   = None, # falls back to EXTERIOR_DESIGN_MODEL / gemini-3.1-flash-image
) -> bytes | None
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from google import genai
from google.genai import types

# Load .env from project root so the service also works standalone
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Defaults — all overridable via .env or function arguments
# ---------------------------------------------------------------------------
_DEFAULT_MODEL = os.getenv("EXTERIOR_DESIGN_MODEL", "gemini-3.1-flash-image")


def _build_prompt(report_text: str, style: Optional[str] = None) -> str:
    style_str = f"Preferred Architectural Style: {style}\n" if style else ""
    return (
        "You are an expert architectural visualizer. Generate a photorealistic, ultra-high-resolution 3D exterior "
        "render of a luxury villa facade based on the provided 2D floor plan drawing and architectural report.\n\n"
        "Requirements:\n"
        f"{style_str}"
        "- Viewpoint: Eye-level or slight 3/4 architectural hero angle showing the front facade and main entrance.\n"
        "- Exterior Aesthetics: Premium exterior finishes, modern stone cladding, wooden louvers/slats, floor-to-ceiling glass windows, and ambient architectural accent lighting.\n"
        "- Context & Surroundings: Elegant boundary wall with modern gate, landscaped front yard with green plants, paved garage driveway.\n"
        "- Lighting & Atmosphere: Warm golden hour or dusk lighting enhancing architectural textures and shadows.\n"
        "- Layout Consistency: Building massing, number of floors, and window positioning MUST align accurately with the attached 2D floor plan and report.\n\n"
        "Architectural Report (Arabic):\n"
        "---\n"
        f"{report_text}\n"
        "---\n\n"
        "Output: a single photorealistic 3D architectural exterior render image. No text captions, no borders, no watermarks."
    )


def generate_exterior_design(
    report_text: str,
    floor_plan_bytes: Optional[bytes] = None,
    style: Optional[str] = None,
    api_key: Optional[str] = None,
    model: Optional[str] = None,
) -> Optional[bytes]:
    """
    Calls Google GenAI API (gemini-3.1-flash-image by default) with multimodal inputs
    (report text + 2D floor plan image) to generate a photorealistic 3D exterior render.

    Parameters
    ----------
    report_text : str
        Full architectural report produced by the main agent.
    floor_plan_bytes : bytes, optional
        Raw byte content of the 2D floor plan image generated by floor_plan_service.
    style : str, optional
        Preferred architectural style (e.g. "طراز سلماني", "مودرن حديث", "نجدي مطور").
    api_key : str, optional
        Gemini API key. Falls back to GEMINI_API_KEY from .env.
    model : str, optional
        Model name. Falls back to EXTERIOR_DESIGN_MODEL env var or 'gemini-3.1-flash-image'.

    Returns
    -------
    bytes or None
    """
    if not report_text:
        logger.warning("exterior_design_service: no report_text provided.")
        return None

    # Resolve key: passed argument wins, then fall back to GEMINI_API_KEY from .env
    resolved_key = api_key or os.getenv("GEMINI_API_KEY", "")
    if not resolved_key:
        raise RuntimeError(
            "No Gemini API key found. "
            "Set GEMINI_API_KEY in .env or pass api_key= to this function."
        )

    resolved_model = model or _DEFAULT_MODEL

    logger.info(
        "exterior_design_service: model=%s | style=%s | has_floor_plan=%s | key_src=%s",
        resolved_model,
        style or "default",
        bool(floor_plan_bytes),
        "parameter" if api_key else "GEMINI_API_KEY env",
    )

    contents: list[str | types.Part] = [_build_prompt(report_text, style)]

    if floor_plan_bytes:
        # Detect mime type if JPEG header present, else default to PNG
        mime_type = "image/jpeg" if floor_plan_bytes.startswith(b"\xff\xd8") else "image/png"
        contents.append(types.Part.from_bytes(data=floor_plan_bytes, mime_type=mime_type))

    client = genai.Client(api_key=resolved_key)
    response = client.models.generate_content(
        model=resolved_model,
        contents=contents,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE"],
        ),
    )

    if response.candidates:
        for part in response.candidates[0].content.parts:
            if hasattr(part, "inline_data") and part.inline_data and part.inline_data.data:
                return part.inline_data.data

    raise RuntimeError("No 3D exterior design image returned from Gemini model generation response.")
